<a href="https://colab.research.google.com/github/SzczotkaMichal/data-science-bootcamp/blob/main/Project1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np

In [17]:
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.array(range(1,11,1))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr = np.zeros(shape=(3,3), dtype=int)

count = 1
for i in range(3):
  for j in range(3):
    arr[i, j] = count
    count += 1

arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
A = np.array([1, 2, 3, 4, 5])
A = np.array([1, 2, 3, 4, 5])
A*2
A+10
A**2

array([ 1,  4,  9, 16, 25])

A = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
Wydrukuj drugi wiersz.
Wydrukuj element w pierwszym wierszu i drugiej kolumnie.
Wydrukuj ostatnią kolumnę.

In [44]:
A = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
A[2]
A[1,2]
print(A[:, -1])

[30 60 90]


In [48]:
A = np.arange(25)
A.reshape(5,5)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
A.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])